### ISSUE TITLE
Implement Net Promoter Landing page

### ISSUE THREAD

**Issue by MiliStJohn** [energycircle/ec_service_review_system#2]
The net promoter landing page is outlined on [this wireframe](https://docs.google.com/drawings/d/1m-uIywMmAOgEJyodyVbROZXY6_gFi9NwpQzOTQkiY28/edit). The landing page will be comprised of basic questions to gauge the users satisfaction with service as well as a final net promoter score. 

The question should be built as basic questions but should be built with the mindset that customers may at some point want to change them.

**Comment by flux423** [comment]
Pushing these to @ec-dchadwick to review with @TWoofenden.
