### ISSUE TITLE
Add Step 2

### ISSUE THREAD

**Issue by MiliStJohn** [energycircle/ec_service_review_system#3]
I am not entirely sure where we landed on this, but I believe we chose to make this one page and have the panels change based on the NP score. If that is not the case, I should separate this into different tasks. 

Overview: The second pane should have multiple functions.

**NP 10-9:** Pane should solicit either 5 star review OR offsite review, and once that is completed, it should show the opposite (EX: 5 Star shown first, then offsite review OR Offsite review and then 5 star review)

**NP 7-8:** Pane should solicit personal info and a comment on service

**NP 0-6:** Pane should solicit same info as 7-8 with separate messaging

<img width="744" alt="screen shot 2016-06-03 at 3 34 55 pm" src="https://cloud.githubusercontent.com/assets/15463763/15790701/c14bd304-29a0-11e6-837f-a6f77819cb27.png">

<img width="511" alt="screen shot 2016-06-03 at 3 37 15 pm" src="https://cloud.githubusercontent.com/assets/15463763/15790756/166265a6-29a1-11e6-87aa-d5eb2b2c7992.png">
<img width="506" alt="screen shot 2016-06-03 at 3 36 53 pm" src="https://cloud.githubusercontent.com/assets/15463763/15790757/166578ae-29a1-11e6-93a5-438f2b371577.png">

https://drive.google.com/drive/folders/0B-NW9Ah_fM0-YkJXeVE3V1JDY1k

**Comment by flux423** [comment]
Has this been reviewed? Can we close these issues?

**Comment by ghost** [comment]
Not entirely sure what else needs to be done here. Seems as though we are not going with the suggested actions above for responders who give a 9 or a 10. A customer who leaves a 9/10 is directed to 1 page where they can leave a review directly, or link out to external. There is no step beyond this and I think that is appropriate. Would be confusing UX to have someone leave a review, then point them to essentially the same page to leave another review. Also the copy to clipboard part doesn't seem intuitive or necessary.

Maybe the solution here is having more developed language on the landing page after rating 9 or 10. Something along the lines of "How did we do? [input box]" then below that, "Having reviews on Google, Angie's List and Yelp are critical for running a successful small business. Please take a minute to share your thoughts on these sites as well, as it will help us grow and create more happy customers like yourself!"

**Comment by flux423** [comment]
This has changed. closing this ticket.
